// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDlMbSLM2ZaJDx64nGpJ1nlMLlCS505Ob0',
    appId: '1:1044228442907:web:40715620213a27d3f3a1be',
    messagingSenderId: '1044228442907',
    projectId: 'newsly-app-yous',
    authDomain: 'newsly-app-yous.firebaseapp.com',
    storageBucket: 'newsly-app-yous.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBUjGbX7fi18SL3h7gyNtOVXnnoIcxaPX4',
    appId: '1:1044228442907:android:490d1c2314158204f3a1be',
    messagingSenderId: '1044228442907',
    projectId: 'newsly-app-yous',
    storageBucket: 'newsly-app-yous.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDH7xtdYboIG5goTOctR9L2cz0dO6JMpPM',
    appId: '1:1044228442907:ios:7049f2ffc7ab5c79f3a1be',
    messagingSenderId: '1044228442907',
    projectId: 'newsly-app-yous',
    storageBucket: 'newsly-app-yous.firebasestorage.app',
    iosBundleId: 'com.example.newsly',
  );
}
